"""Bounded single-request HTTP/1.1 connection; no bind/listen or approval grant.

Called only by the future managed, approval-gated web listener. Duplicate
headers survive parsing. No keep-alive, pipelined second action or retry.
"""
import math
import re
import time
from web_proxy import WebProxy, TOKEN

HEADER_LIMIT = 16384
BODY_LIMIT = 16384


def handle_connection(stream, peer, proxy, exchange, *, clock=time.monotonic,
                      stop=lambda: False):
    """Own and close stream on every exit, including cancellation and panic.

    Five seconds cover request, upstream and response; the upstream separately
    enforces its two-second budget. Errors close without diagnostic output.
    False never proves absence of an upstream effect.
    """
    try:
        if not isinstance(proxy, WebProxy) or peer not in ('127.0.0.1', '::1'):
            raise ValueError('WEB_CONNECTION_INPUT')
        previous = clock()
        if not math.isfinite(previous):
            raise ValueError('WEB_CLOCK')
        deadline = previous + 5.0

        def remaining():
            nonlocal previous
            now = clock()
            if stop() or not math.isfinite(now) or now < previous or now >= deadline:
                raise TimeoutError('WEB_DEADLINE')
            previous = now
            return deadline - now

        consumed = 0

        def read(size):
            stream.settimeout(remaining())
            raw = stream.recv(size)
            if type(raw) is not bytes or not 0 < len(raw) <= size:
                raise ValueError('WEB_EOF')
            remaining()
            return raw

        def line():
            nonlocal consumed
            raw = bytearray()
            while len(raw) < 4096 and consumed < HEADER_LIMIT:
                raw.extend(read(1))
                consumed += 1
                if raw[-1] == 10:
                    if not raw.endswith(b'\r\n'):
                        raise ValueError('WEB_FRAMING')
                    return bytes(raw[:-2]).decode('ascii')
            raise ValueError('WEB_HEADER_LIMIT')

        request = line()
        if not re.fullmatch(r'(GET|HEAD|POST) /[\x21-\x7e]* HTTP/1\.1', request):
            raise ValueError('WEB_REQUEST')
        method, target, _ = request.split(' ')
        headers = []
        while True:
            row = line()
            if not row:
                break
            key, sep, value = row.partition(':')
            if (len(headers) >= 32 or not sep or not TOKEN.fullmatch(key) or
                any(ord(c) < 32 or ord(c) >= 127 for c in value)):
                raise ValueError('WEB_HEADER')
            headers.append((key, value.strip(' ')))
        fields = lambda name: [v for k, v in headers if k.lower() == name]
        lengths = fields('content-length')
        if (any(fields(k) for k in ('transfer-encoding', 'expect', 'upgrade')) or
            len(lengths) > 1 or (lengths and not re.fullmatch(r'0|[1-9][0-9]{0,4}', lengths[0])) or
            (method == 'POST' and not lengths)):
            raise ValueError('WEB_FRAMING')
        size = int(lengths[0]) if lengths else 0
        if size > BODY_LIMIT or (method != 'POST' and size):
            raise ValueError('WEB_BODY_LIMIT')
        body = bytearray()
        while len(body) < size:
            body.extend(read(min(4096, size-len(body))))
        remaining()
        status, response_headers, response = proxy.respond(
            method, target, headers, bytes(body), peer, exchange)
        remaining()
        # All response headers are generated by StaticWeb, never client strings.
        wire = (f'HTTP/1.1 {status} Response\r\n' + ''.join(
            f'{key}: {value}\r\n' for key, value in response_headers.items()) +
            'Connection: close\r\n\r\n').encode('ascii') + response
        at = 0
        while at < len(wire):
            stream.settimeout(remaining())
            sent = stream.send(wire[at:at+65536])
            if type(sent) is not int or not 0 < sent <= min(65536, len(wire)-at):
                raise ValueError('WEB_SEND')
            at += sent
        remaining()
        return True
    except Exception:
        return False
    finally:
        stream.close()


def serve_listener(listener, proxy, exchange, *, max_requests, lifetime_seconds,
                   stop, clock=time.monotonic):
    """Own a pre-bound listener; caller must first pass managed approval gates.

    Sequential connections only. At most one request per accepted socket. An IO
    or parsing failure terminates this lane; no accept/retry after that failure.
    This function neither binds a socket nor establishes organizational approval.
    """
    import socket
    handled = 0
    try:
        if (not isinstance(proxy, WebProxy) or type(max_requests) is not int or
            not 1 <= max_requests <= 10000 or type(lifetime_seconds) is not int or
            not 1 <= lifetime_seconds <= 3600 or
            listener.family != socket.AF_INET or listener.type != socket.SOCK_STREAM or
            listener.getsockname() != ('127.0.0.1', 5173)):
            raise ValueError('WEB_LISTENER_INPUT')
        started = clock()
        if not math.isfinite(started):
            raise ValueError('WEB_CLOCK')
        previous = started
        deadline = started + lifetime_seconds
        def ended():
            nonlocal previous
            now = clock()
            if not math.isfinite(now) or now < previous:
                raise ValueError('WEB_CLOCK')
            previous = now
            return stop() or now >= deadline
        while handled < max_requests:
            if ended():
                break
            listener.settimeout(min(0.2, deadline-previous))
            try:
                stream, address = listener.accept()
            except TimeoutError:
                continue  # Idle accept only; never repeat a request/effect.
            try:
                stopping = ended()
            except BaseException:
                stream.close()
                raise
            if stopping:
                stream.close()
                break
            if type(address) is not tuple or len(address) != 2:
                stream.close()
                raise ValueError('WEB_PEER')
            if not handle_connection(stream, address[0], proxy, exchange,
                                     clock=clock, stop=ended):
                raise ValueError('WEB_CONNECTION_FAILED')
            handled += 1
        return {'handled_connections': handled, 'listener_closed': True,
                'approval_verified': False}
    finally:
        listener.close()
