// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: nus/exchange/s3/v1/tx.proto

package s3types

import (
	context "context"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-sdk/types/msgservice"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// Additive SDK messages. User Order/Cancel/Wallet/FillIdentity V1 stay unchanged.
// SDK protobuf: omitted scalar zero follows SIGN_MODE_DIRECT rules.
// batch_wire is strict canonical nus.protocol.s3.BatchV2, NOT protobuf JSON.
type MsgSettleBatch struct {
	Operator             string   `protobuf:"bytes,1,opt,name=operator,proto3" json:"operator,omitempty"`
	BatchWire            []byte   `protobuf:"bytes,2,opt,name=batch_wire,json=batchWire,proto3" json:"batch_wire,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MsgSettleBatch) Reset()         { *m = MsgSettleBatch{} }
func (m *MsgSettleBatch) String() string { return proto.CompactTextString(m) }
func (*MsgSettleBatch) ProtoMessage()    {}
func (*MsgSettleBatch) Descriptor() ([]byte, []int) {
	return fileDescriptor_e08f69ed68308353, []int{0}
}
func (m *MsgSettleBatch) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgSettleBatch.Unmarshal(m, b)
}
func (m *MsgSettleBatch) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgSettleBatch.Marshal(b, m, deterministic)
}
func (m *MsgSettleBatch) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgSettleBatch.Merge(m, src)
}
func (m *MsgSettleBatch) XXX_Size() int {
	return xxx_messageInfo_MsgSettleBatch.Size(m)
}
func (m *MsgSettleBatch) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgSettleBatch.DiscardUnknown(m)
}

var xxx_messageInfo_MsgSettleBatch proto.InternalMessageInfo

func (m *MsgSettleBatch) GetOperator() string {
	if m != nil {
		return m.Operator
	}
	return ""
}

func (m *MsgSettleBatch) GetBatchWire() []byte {
	if m != nil {
		return m.BatchWire
	}
	return nil
}

type MsgCloseBatch struct {
	Operator               string   `protobuf:"bytes,1,opt,name=operator,proto3" json:"operator,omitempty"`
	BatchWire              []byte   `protobuf:"bytes,2,opt,name=batch_wire,json=batchWire,proto3" json:"batch_wire,omitempty"`
	FailedTxHash           []byte   `protobuf:"bytes,3,opt,name=failed_tx_hash,json=failedTxHash,proto3" json:"failed_tx_hash,omitempty"`
	ResolutionEvidenceHash []byte   `protobuf:"bytes,4,opt,name=resolution_evidence_hash,json=resolutionEvidenceHash,proto3" json:"resolution_evidence_hash,omitempty"`
	XXX_NoUnkeyedLiteral   struct{} `json:"-"`
	XXX_unrecognized       []byte   `json:"-"`
	XXX_sizecache          int32    `json:"-"`
}

func (m *MsgCloseBatch) Reset()         { *m = MsgCloseBatch{} }
func (m *MsgCloseBatch) String() string { return proto.CompactTextString(m) }
func (*MsgCloseBatch) ProtoMessage()    {}
func (*MsgCloseBatch) Descriptor() ([]byte, []int) {
	return fileDescriptor_e08f69ed68308353, []int{1}
}
func (m *MsgCloseBatch) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgCloseBatch.Unmarshal(m, b)
}
func (m *MsgCloseBatch) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgCloseBatch.Marshal(b, m, deterministic)
}
func (m *MsgCloseBatch) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgCloseBatch.Merge(m, src)
}
func (m *MsgCloseBatch) XXX_Size() int {
	return xxx_messageInfo_MsgCloseBatch.Size(m)
}
func (m *MsgCloseBatch) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgCloseBatch.DiscardUnknown(m)
}

var xxx_messageInfo_MsgCloseBatch proto.InternalMessageInfo

func (m *MsgCloseBatch) GetOperator() string {
	if m != nil {
		return m.Operator
	}
	return ""
}

func (m *MsgCloseBatch) GetBatchWire() []byte {
	if m != nil {
		return m.BatchWire
	}
	return nil
}

func (m *MsgCloseBatch) GetFailedTxHash() []byte {
	if m != nil {
		return m.FailedTxHash
	}
	return nil
}

func (m *MsgCloseBatch) GetResolutionEvidenceHash() []byte {
	if m != nil {
		return m.ResolutionEvidenceHash
	}
	return nil
}

type MsgRotateSettlementOperator struct {
	Authority            string   `protobuf:"bytes,1,opt,name=authority,proto3" json:"authority,omitempty"`
	ExpectedEpoch        uint64   `protobuf:"varint,2,opt,name=expected_epoch,json=expectedEpoch,proto3" json:"expected_epoch,omitempty"`
	NewOperatorPubkey    []byte   `protobuf:"bytes,3,opt,name=new_operator_pubkey,json=newOperatorPubkey,proto3" json:"new_operator_pubkey,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MsgRotateSettlementOperator) Reset()         { *m = MsgRotateSettlementOperator{} }
func (m *MsgRotateSettlementOperator) String() string { return proto.CompactTextString(m) }
func (*MsgRotateSettlementOperator) ProtoMessage()    {}
func (*MsgRotateSettlementOperator) Descriptor() ([]byte, []int) {
	return fileDescriptor_e08f69ed68308353, []int{2}
}
func (m *MsgRotateSettlementOperator) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgRotateSettlementOperator.Unmarshal(m, b)
}
func (m *MsgRotateSettlementOperator) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgRotateSettlementOperator.Marshal(b, m, deterministic)
}
func (m *MsgRotateSettlementOperator) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgRotateSettlementOperator.Merge(m, src)
}
func (m *MsgRotateSettlementOperator) XXX_Size() int {
	return xxx_messageInfo_MsgRotateSettlementOperator.Size(m)
}
func (m *MsgRotateSettlementOperator) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgRotateSettlementOperator.DiscardUnknown(m)
}

var xxx_messageInfo_MsgRotateSettlementOperator proto.InternalMessageInfo

func (m *MsgRotateSettlementOperator) GetAuthority() string {
	if m != nil {
		return m.Authority
	}
	return ""
}

func (m *MsgRotateSettlementOperator) GetExpectedEpoch() uint64 {
	if m != nil {
		return m.ExpectedEpoch
	}
	return 0
}

func (m *MsgRotateSettlementOperator) GetNewOperatorPubkey() []byte {
	if m != nil {
		return m.NewOperatorPubkey
	}
	return nil
}

type MsgRevokeOrder struct {
	Owner                string   `protobuf:"bytes,1,opt,name=owner,proto3" json:"owner,omitempty"`
	OrderHash            []byte   `protobuf:"bytes,2,opt,name=order_hash,json=orderHash,proto3" json:"order_hash,omitempty"`
	ExpectedEpoch        uint64   `protobuf:"varint,3,opt,name=expected_epoch,json=expectedEpoch,proto3" json:"expected_epoch,omitempty"`
	RequestId            []byte   `protobuf:"bytes,4,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	ExpiryHeight         uint64   `protobuf:"varint,5,opt,name=expiry_height,json=expiryHeight,proto3" json:"expiry_height,omitempty"`
	GenesisHash          []byte   `protobuf:"bytes,6,opt,name=genesis_hash,json=genesisHash,proto3" json:"genesis_hash,omitempty"`
	OrderWire            []byte   `protobuf:"bytes,7,opt,name=order_wire,json=orderWire,proto3" json:"order_wire,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MsgRevokeOrder) Reset()         { *m = MsgRevokeOrder{} }
func (m *MsgRevokeOrder) String() string { return proto.CompactTextString(m) }
func (*MsgRevokeOrder) ProtoMessage()    {}
func (*MsgRevokeOrder) Descriptor() ([]byte, []int) {
	return fileDescriptor_e08f69ed68308353, []int{3}
}
func (m *MsgRevokeOrder) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgRevokeOrder.Unmarshal(m, b)
}
func (m *MsgRevokeOrder) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgRevokeOrder.Marshal(b, m, deterministic)
}
func (m *MsgRevokeOrder) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgRevokeOrder.Merge(m, src)
}
func (m *MsgRevokeOrder) XXX_Size() int {
	return xxx_messageInfo_MsgRevokeOrder.Size(m)
}
func (m *MsgRevokeOrder) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgRevokeOrder.DiscardUnknown(m)
}

var xxx_messageInfo_MsgRevokeOrder proto.InternalMessageInfo

func (m *MsgRevokeOrder) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

func (m *MsgRevokeOrder) GetOrderHash() []byte {
	if m != nil {
		return m.OrderHash
	}
	return nil
}

func (m *MsgRevokeOrder) GetExpectedEpoch() uint64 {
	if m != nil {
		return m.ExpectedEpoch
	}
	return 0
}

func (m *MsgRevokeOrder) GetRequestId() []byte {
	if m != nil {
		return m.RequestId
	}
	return nil
}

func (m *MsgRevokeOrder) GetExpiryHeight() uint64 {
	if m != nil {
		return m.ExpiryHeight
	}
	return 0
}

func (m *MsgRevokeOrder) GetGenesisHash() []byte {
	if m != nil {
		return m.GenesisHash
	}
	return nil
}

func (m *MsgRevokeOrder) GetOrderWire() []byte {
	if m != nil {
		return m.OrderWire
	}
	return nil
}

type MsgBumpOrderEpoch struct {
	Owner                string   `protobuf:"bytes,1,opt,name=owner,proto3" json:"owner,omitempty"`
	ExpectedEpoch        uint64   `protobuf:"varint,2,opt,name=expected_epoch,json=expectedEpoch,proto3" json:"expected_epoch,omitempty"`
	RequestId            []byte   `protobuf:"bytes,3,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	ExpiryHeight         uint64   `protobuf:"varint,4,opt,name=expiry_height,json=expiryHeight,proto3" json:"expiry_height,omitempty"`
	GenesisHash          []byte   `protobuf:"bytes,5,opt,name=genesis_hash,json=genesisHash,proto3" json:"genesis_hash,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MsgBumpOrderEpoch) Reset()         { *m = MsgBumpOrderEpoch{} }
func (m *MsgBumpOrderEpoch) String() string { return proto.CompactTextString(m) }
func (*MsgBumpOrderEpoch) ProtoMessage()    {}
func (*MsgBumpOrderEpoch) Descriptor() ([]byte, []int) {
	return fileDescriptor_e08f69ed68308353, []int{4}
}
func (m *MsgBumpOrderEpoch) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgBumpOrderEpoch.Unmarshal(m, b)
}
func (m *MsgBumpOrderEpoch) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgBumpOrderEpoch.Marshal(b, m, deterministic)
}
func (m *MsgBumpOrderEpoch) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgBumpOrderEpoch.Merge(m, src)
}
func (m *MsgBumpOrderEpoch) XXX_Size() int {
	return xxx_messageInfo_MsgBumpOrderEpoch.Size(m)
}
func (m *MsgBumpOrderEpoch) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgBumpOrderEpoch.DiscardUnknown(m)
}

var xxx_messageInfo_MsgBumpOrderEpoch proto.InternalMessageInfo

func (m *MsgBumpOrderEpoch) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

func (m *MsgBumpOrderEpoch) GetExpectedEpoch() uint64 {
	if m != nil {
		return m.ExpectedEpoch
	}
	return 0
}

func (m *MsgBumpOrderEpoch) GetRequestId() []byte {
	if m != nil {
		return m.RequestId
	}
	return nil
}

func (m *MsgBumpOrderEpoch) GetExpiryHeight() uint64 {
	if m != nil {
		return m.ExpiryHeight
	}
	return 0
}

func (m *MsgBumpOrderEpoch) GetGenesisHash() []byte {
	if m != nil {
		return m.GenesisHash
	}
	return nil
}

type MsgResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MsgResponse) Reset()         { *m = MsgResponse{} }
func (m *MsgResponse) String() string { return proto.CompactTextString(m) }
func (*MsgResponse) ProtoMessage()    {}
func (*MsgResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e08f69ed68308353, []int{5}
}
func (m *MsgResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgResponse.Unmarshal(m, b)
}
func (m *MsgResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgResponse.Marshal(b, m, deterministic)
}
func (m *MsgResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgResponse.Merge(m, src)
}
func (m *MsgResponse) XXX_Size() int {
	return xxx_messageInfo_MsgResponse.Size(m)
}
func (m *MsgResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*MsgSettleBatch)(nil), "nus.exchange.s3.v1.MsgSettleBatch")
	proto.RegisterType((*MsgCloseBatch)(nil), "nus.exchange.s3.v1.MsgCloseBatch")
	proto.RegisterType((*MsgRotateSettlementOperator)(nil), "nus.exchange.s3.v1.MsgRotateSettlementOperator")
	proto.RegisterType((*MsgRevokeOrder)(nil), "nus.exchange.s3.v1.MsgRevokeOrder")
	proto.RegisterType((*MsgBumpOrderEpoch)(nil), "nus.exchange.s3.v1.MsgBumpOrderEpoch")
	proto.RegisterType((*MsgResponse)(nil), "nus.exchange.s3.v1.MsgResponse")
}

func init() { proto.RegisterFile("nus/exchange/s3/v1/tx.proto", fileDescriptor_e08f69ed68308353) }

var fileDescriptor_e08f69ed68308353 = []byte{
	// 618 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x54, 0xcd, 0x6a, 0xdb, 0x4c,
	0x14, 0x45, 0x9f, 0xe3, 0x7c, 0xf5, 0xf5, 0x0f, 0x64, 0x5a, 0x5a, 0xe3, 0x34, 0x34, 0x71, 0x1b,
	0x08, 0x81, 0x48, 0xa4, 0xd9, 0x94, 0xd0, 0x55, 0x4a, 0x20, 0x5d, 0x98, 0x04, 0xb5, 0xd0, 0x92,
	0x8d, 0x90, 0xa5, 0xdb, 0xd1, 0x10, 0x6b, 0x46, 0xd5, 0x8c, 0x6c, 0x79, 0x57, 0xfa, 0x28, 0x7d,
	0x82, 0x6c, 0xbb, 0xee, 0xbe, 0xaf, 0x91, 0xb7, 0x28, 0x45, 0x23, 0xc9, 0x3f, 0x49, 0x84, 0x03,
	0x5d, 0xce, 0xb9, 0x67, 0xee, 0x9c, 0x73, 0x66, 0xee, 0xc0, 0x26, 0x4f, 0xa4, 0x85, 0xa9, 0x17,
	0xb8, 0x9c, 0xa2, 0x25, 0x8f, 0xac, 0xf1, 0xa1, 0xa5, 0x52, 0x33, 0x8a, 0x85, 0x12, 0x84, 0xf0,
	0x44, 0x9a, 0x65, 0xd1, 0x94, 0x47, 0xe6, 0xf8, 0xb0, 0xf7, 0xcc, 0x13, 0x32, 0x14, 0xd2, 0x0a,
	0x25, 0xcd, 0xb8, 0xa1, 0xa4, 0x39, 0xb9, 0x7f, 0x09, 0x9d, 0x81, 0xa4, 0x1f, 0x50, 0xa9, 0x11,
	0x9e, 0xb8, 0xca, 0x0b, 0x48, 0x0f, 0x1e, 0x89, 0x08, 0x63, 0x57, 0x89, 0xb8, 0x6b, 0x6c, 0x1b,
	0x7b, 0x0d, 0x7b, 0xb6, 0x26, 0x5b, 0x00, 0xc3, 0x8c, 0xe4, 0x4c, 0x58, 0x8c, 0xdd, 0xff, 0xb6,
	0x8d, 0xbd, 0x96, 0xdd, 0xd0, 0xc8, 0x27, 0x16, 0xe3, 0x71, 0xfb, 0xfb, 0xcd, 0xf5, 0xfe, 0x8c,
	0xdd, 0xff, 0x69, 0x40, 0x7b, 0x20, 0xe9, 0xbb, 0x91, 0x90, 0xff, 0xdc, 0x9b, 0xbc, 0x82, 0xce,
	0x17, 0x97, 0x8d, 0xd0, 0x77, 0x54, 0xea, 0x04, 0xae, 0x0c, 0xba, 0x35, 0x4d, 0x69, 0xe5, 0xe8,
	0xc7, 0xf4, 0xcc, 0x95, 0x01, 0x79, 0x03, 0xdd, 0x18, 0xa5, 0x18, 0x25, 0x8a, 0x09, 0xee, 0xe0,
	0x98, 0xf9, 0xc8, 0x3d, 0xcc, 0xf9, 0x6b, 0x9a, 0xff, 0x74, 0x5e, 0x3f, 0x2d, 0xca, 0xd9, 0xce,
	0xdb, 0xda, 0x7f, 0x18, 0xb0, 0x39, 0x90, 0xd4, 0x16, 0xca, 0x55, 0x98, 0xc7, 0x13, 0x22, 0x57,
	0xe7, 0xa5, 0xda, 0xe7, 0xd0, 0x70, 0x13, 0x15, 0x88, 0x98, 0xa9, 0x69, 0x61, 0x65, 0x0e, 0x90,
	0x5d, 0xe8, 0x60, 0x1a, 0xa1, 0xa7, 0xd0, 0x77, 0x30, 0x12, 0x5e, 0xa0, 0xfd, 0xac, 0xd9, 0xed,
	0x12, 0x3d, 0xcd, 0x40, 0x62, 0xc2, 0x63, 0x8e, 0x13, 0xa7, 0x3c, 0xd4, 0x89, 0x92, 0xe1, 0x15,
	0x4e, 0x0b, 0x63, 0x1b, 0x1c, 0x27, 0xe5, 0x71, 0x17, 0xba, 0x70, 0xdc, 0xc9, 0x34, 0xce, 0x8f,
	0xe9, 0xff, 0x31, 0xf4, 0xed, 0xd9, 0x38, 0x16, 0x57, 0x78, 0x1e, 0xfb, 0x18, 0x93, 0x27, 0x50,
	0x17, 0x13, 0x8e, 0x65, 0xbc, 0xf9, 0x22, 0xcb, 0x56, 0x64, 0xe5, 0x3c, 0x88, 0x22, 0x5b, 0x8d,
	0xe8, 0xd4, 0xee, 0xca, 0xad, 0xdd, 0x27, 0x77, 0x0b, 0x20, 0xc6, 0xaf, 0x09, 0x4a, 0xe5, 0x30,
	0xbf, 0x88, 0xb3, 0x51, 0x20, 0xef, 0x7d, 0xf2, 0x12, 0x32, 0x3e, 0x8b, 0xa7, 0x4e, 0x80, 0x8c,
	0x06, 0xaa, 0x5b, 0xd7, 0x4d, 0x5a, 0x39, 0x78, 0xa6, 0x31, 0xb2, 0x03, 0x2d, 0x8a, 0x1c, 0x25,
	0x93, 0xb9, 0x96, 0x75, 0xdd, 0xa5, 0x59, 0x60, 0x5a, 0xcd, 0x4c, 0xac, 0x7e, 0x08, 0xff, 0x2f,
	0x88, 0xd5, 0x8f, 0x0c, 0xb2, 0x10, 0x72, 0x5f, 0xfd, 0x5f, 0x06, 0x6c, 0x0c, 0x24, 0x3d, 0x49,
	0xc2, 0x48, 0xdb, 0xcf, 0x75, 0xde, 0x9f, 0xc1, 0x03, 0xef, 0x64, 0xd9, 0x64, 0x6d, 0xa5, 0xc9,
	0xb5, 0x07, 0x98, 0xac, 0xdf, 0x31, 0xb9, 0xe4, 0xa2, 0x0d, 0x4d, 0x7d, 0x8b, 0x32, 0x12, 0x5c,
	0xe2, 0xeb, 0xdf, 0x35, 0xa8, 0x0d, 0x24, 0x25, 0x36, 0x34, 0x17, 0xe7, 0xb2, 0x6f, 0xde, 0x9d,
	0x6b, 0x73, 0x79, 0x76, 0x7b, 0x2f, 0x2a, 0x38, 0x65, 0x6f, 0x72, 0x01, 0xb0, 0x30, 0x8e, 0x3b,
	0x15, 0xf4, 0x39, 0x65, 0x75, 0xc7, 0x11, 0x74, 0x2b, 0x87, 0xc4, 0xaa, 0xda, 0x5c, 0xb1, 0x61,
	0xf5, 0x69, 0x36, 0x34, 0x17, 0x5f, 0x7b, 0xbf, 0x92, 0x3f, 0xe3, 0xac, 0xee, 0xf9, 0x19, 0x3a,
	0xb7, 0x1e, 0xd0, 0x6e, 0xc5, 0x96, 0x65, 0xda, 0xca, 0xce, 0xbd, 0xfa, 0xb7, 0x9b, 0xeb, 0x7d,
	0xe3, 0xe4, 0xed, 0xe5, 0x31, 0x65, 0x2a, 0x48, 0x86, 0xa6, 0x27, 0x42, 0x8b, 0x27, 0xf2, 0x80,
	0xba, 0x9c, 0x5a, 0xfa, 0x4b, 0x3e, 0xf0, 0x31, 0xb5, 0xbc, 0xc0, 0x65, 0xdc, 0x72, 0xa3, 0xc8,
	0x4a, 0x17, 0x7f, 0x75, 0x35, 0x8d, 0x50, 0x0e, 0xd7, 0xf5, 0x47, 0x7d, 0xf4, 0x37, 0x00, 0x00,
	0xff, 0xff, 0x93, 0x7f, 0x01, 0x2d, 0xf4, 0x05, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MsgClient interface {
	SettleBatch(ctx context.Context, in *MsgSettleBatch, opts ...grpc.CallOption) (*MsgResponse, error)
	CloseBatch(ctx context.Context, in *MsgCloseBatch, opts ...grpc.CallOption) (*MsgResponse, error)
	RotateSettlementOperator(ctx context.Context, in *MsgRotateSettlementOperator, opts ...grpc.CallOption) (*MsgResponse, error)
	RevokeOrder(ctx context.Context, in *MsgRevokeOrder, opts ...grpc.CallOption) (*MsgResponse, error)
	BumpOrderEpoch(ctx context.Context, in *MsgBumpOrderEpoch, opts ...grpc.CallOption) (*MsgResponse, error)
}

type msgClient struct {
	cc grpc1.ClientConn
}

func NewMsgClient(cc grpc1.ClientConn) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) SettleBatch(ctx context.Context, in *MsgSettleBatch, opts ...grpc.CallOption) (*MsgResponse, error) {
	out := new(MsgResponse)
	err := c.cc.Invoke(ctx, "/nus.exchange.s3.v1.Msg/SettleBatch", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) CloseBatch(ctx context.Context, in *MsgCloseBatch, opts ...grpc.CallOption) (*MsgResponse, error) {
	out := new(MsgResponse)
	err := c.cc.Invoke(ctx, "/nus.exchange.s3.v1.Msg/CloseBatch", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) RotateSettlementOperator(ctx context.Context, in *MsgRotateSettlementOperator, opts ...grpc.CallOption) (*MsgResponse, error) {
	out := new(MsgResponse)
	err := c.cc.Invoke(ctx, "/nus.exchange.s3.v1.Msg/RotateSettlementOperator", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) RevokeOrder(ctx context.Context, in *MsgRevokeOrder, opts ...grpc.CallOption) (*MsgResponse, error) {
	out := new(MsgResponse)
	err := c.cc.Invoke(ctx, "/nus.exchange.s3.v1.Msg/RevokeOrder", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) BumpOrderEpoch(ctx context.Context, in *MsgBumpOrderEpoch, opts ...grpc.CallOption) (*MsgResponse, error) {
	out := new(MsgResponse)
	err := c.cc.Invoke(ctx, "/nus.exchange.s3.v1.Msg/BumpOrderEpoch", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
type MsgServer interface {
	SettleBatch(context.Context, *MsgSettleBatch) (*MsgResponse, error)
	CloseBatch(context.Context, *MsgCloseBatch) (*MsgResponse, error)
	RotateSettlementOperator(context.Context, *MsgRotateSettlementOperator) (*MsgResponse, error)
	RevokeOrder(context.Context, *MsgRevokeOrder) (*MsgResponse, error)
	BumpOrderEpoch(context.Context, *MsgBumpOrderEpoch) (*MsgResponse, error)
}

// UnimplementedMsgServer can be embedded to have forward compatible implementations.
type UnimplementedMsgServer struct {
}

func (*UnimplementedMsgServer) SettleBatch(ctx context.Context, req *MsgSettleBatch) (*MsgResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SettleBatch not implemented")
}
func (*UnimplementedMsgServer) CloseBatch(ctx context.Context, req *MsgCloseBatch) (*MsgResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CloseBatch not implemented")
}
func (*UnimplementedMsgServer) RotateSettlementOperator(ctx context.Context, req *MsgRotateSettlementOperator) (*MsgResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RotateSettlementOperator not implemented")
}
func (*UnimplementedMsgServer) RevokeOrder(ctx context.Context, req *MsgRevokeOrder) (*MsgResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RevokeOrder not implemented")
}
func (*UnimplementedMsgServer) BumpOrderEpoch(ctx context.Context, req *MsgBumpOrderEpoch) (*MsgResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BumpOrderEpoch not implemented")
}

func RegisterMsgServer(s grpc1.Server, srv MsgServer) {
	s.RegisterService(&_Msg_serviceDesc, srv)
}

func _Msg_SettleBatch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgSettleBatch)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).SettleBatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/nus.exchange.s3.v1.Msg/SettleBatch",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).SettleBatch(ctx, req.(*MsgSettleBatch))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_CloseBatch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgCloseBatch)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).CloseBatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/nus.exchange.s3.v1.Msg/CloseBatch",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).CloseBatch(ctx, req.(*MsgCloseBatch))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_RotateSettlementOperator_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgRotateSettlementOperator)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).RotateSettlementOperator(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/nus.exchange.s3.v1.Msg/RotateSettlementOperator",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).RotateSettlementOperator(ctx, req.(*MsgRotateSettlementOperator))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_RevokeOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgRevokeOrder)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).RevokeOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/nus.exchange.s3.v1.Msg/RevokeOrder",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).RevokeOrder(ctx, req.(*MsgRevokeOrder))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_BumpOrderEpoch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgBumpOrderEpoch)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).BumpOrderEpoch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/nus.exchange.s3.v1.Msg/BumpOrderEpoch",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).BumpOrderEpoch(ctx, req.(*MsgBumpOrderEpoch))
	}
	return interceptor(ctx, in, info, handler)
}

var Msg_serviceDesc = _Msg_serviceDesc
var _Msg_serviceDesc = grpc.ServiceDesc{
	ServiceName: "nus.exchange.s3.v1.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SettleBatch",
			Handler:    _Msg_SettleBatch_Handler,
		},
		{
			MethodName: "CloseBatch",
			Handler:    _Msg_CloseBatch_Handler,
		},
		{
			MethodName: "RotateSettlementOperator",
			Handler:    _Msg_RotateSettlementOperator_Handler,
		},
		{
			MethodName: "RevokeOrder",
			Handler:    _Msg_RevokeOrder_Handler,
		},
		{
			MethodName: "BumpOrderEpoch",
			Handler:    _Msg_BumpOrderEpoch_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "nus/exchange/s3/v1/tx.proto",
}
